# Generated by Django 3.1.7 on 2021-03-15 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("booktest", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="bookinfo",
            name="pub_date",
            field=models.DateField(help_text="出版日期"),
        ),
        migrations.AlterField(
            model_name="bookinfo",
            name="title",
            field=models.CharField(help_text="图书名称", max_length=20),
        ),
        migrations.CreateModel(
            name="HeroInfo",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="英雄名", max_length=50)),
                ("age", models.IntegerField(help_text="英雄性别")),
                ("gender", models.IntegerField(help_text="英雄性别")),
                ("comment", models.CharField(help_text="备注", max_length=255)),
                (
                    "hero_book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="book",
                        to="booktest.bookinfo",
                    ),
                ),
            ],
        ),
    ]
